name: Deploy React Project to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Cambia esto si usas otra versión de Node.js

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Compilar el proyecto de React (TypeScript)
      - name: Build React Project
        run: npm run build

      # 5. Subir archivos a S3
      - name: Deploy to S3
        run: aws s3 sync build/ s3://panel.mnprogram.com --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # Cambia según la región de tu bucket S3

      # 6. Invalidar caché de CloudFront
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ESDEN5L92Y3IK --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
